### ISSUE TITLE
Link to OPENI2

### ISSUE THREAD

**Issue by vladsterz** [robotics-4-all/skeleton_tracker#1]
export OPENNI2_INCLUDE=/home/klpanagi/Desktop/OpenNI2/Packaging/OpenNI-Linux-x64-2.2/Include
export OPENNI2_REDIST=/home/klpanagi/Desktop/OpenNI2/Packaging/OpenNI-Linux-x64-2.2/Redist

should be:

export OPENNI2_INCLUDE=/home/klpanagi/Desktop/OpenNI2/Include
export OPENNI2_REDIST=/home/klpanagi/Desktop/OpenNI2/Redist

**Comment by klpanagi** [comment]
Follow the instructions [here](https://github.com/robotics-4-all/skeleton_tracker) on how to build OpenNI2  for your machine (non-cross-compilation).

Resolved!
